### PR TITLE
Index Grammar/Clarity Pass

### PR DESCRIPTION
**Pull request by seandenigris**

### CODE REVIEW

**Comment by SergeStinckwich** [comment]
Can we integrate?

**Comment by seandenigris** [comment]
Maybe @Ducasse is still on holidays?

**Comment by seandenigris** [comment]
Another easy one... @Ducasse

**Comment by seandenigris** [comment]
Chasing down old PRs. @Ducasse can we merge this?

**Comment by seandenigris** [comment]
Thanks @Ducasse!

**Pull request merged**
